name: ESLint & Prettier

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-eslint-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-eslint-
      - name: yarn install
        run: yarn install
      - name: Run eslint & prettier
        run: yarn lint:check
